---
name: JB0TS QA Loop

on:
  push:
    paths:
      - 'engine/**'
      - 'spec1_benchmark/**'
      - 'memory_qa/**'
      - '.j0nb0t/**'
      - '.j$0nb0t/**'
      - 'scripts/**'
      - 'intelligence_hooks/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JB0TS Validation
        run: |
          echo "[QA] Running JB0TS validation..."
          python3 ./spec1_benchmark/validate_cognition.py || echo "[QA] Validation script missing or failed"
